basePath: https://internal.icg.co.id/rosi

spring:
  datasource:
    url: jdbc:mysql://192.168.1.6:3306/rosi
    username: alif
    password: icg123456
    driver-class-name: com.mysql.jdbc.Driver

debug: false

file:
  location : /home/alif/livingworld/images/


